
CREATE TABLE IF NOT EXISTS SOCCER_TEAM (
name VARCHAR(250) NOT NULL,
league VARCHAR(250) NOT NULL,
championships VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS PERSON (
 name VARCHAR(250) NOT NULL,
 lastname VARCHAR(250) NOT NULL
);


